# Generated by Django 5.0 on 2023-12-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_parent_post_view_count_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
