# Generated by Django 5.0 on 2024-01-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_author'),
        ('users', '0002_remove_user_login_id_user_last_login_user_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
